import json

# Reasoning generated by applying the directional cause->effect / prerequisite prompt
# to each (text_1, text_2) pair. Keyed by line index (0-based).
reasoning = {
    0: "no relation",
    1: "no relation",
    2: "Understanding Journey Optimizer's API-first architecture and the role of the Marketer persona provides the conceptual foundation a practitioner needs before they can meaningfully step into the platform and author multi-action campaign content, run experiments across channels, and activate those campaigns.",
    3: "no relation",
    4: "no relation",
    5: "no relation",
    6: "no relation",
    7: "Setting up an S3 source connection, authenticating it, and ingesting a source file brings customer profile attributes — such as email addresses and marketing use-case IDs — into the platform, and only once those attributes exist on a profile can you define audience conditions that filter and group people based on them.",
    8: "Enabling supplemental identifiers allows a profile to reenter a journey using a contextual key like a product ID, and that reentry mechanism is the prerequisite for building a multi-step product-view and add-to-cart reminder journey — without it, a profile can only pass through the sequence once and cannot be tracked independently for each new product interaction.",
    9: "no relation",
}

inp = "directional_train_sample10_label1.jsonl"
out = "directional_train_sample10_label1_with_reasoning.jsonl"

with open(inp) as f:
    rows = [json.loads(l) for l in f if l.strip()]

assert len(rows) == len(reasoning), f"row/reasoning mismatch: {len(rows)} vs {len(reasoning)}"

with open(out, "w") as f:
    for i, r in enumerate(rows):
        r["reasoning"] = reasoning[i]
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

print(f"Wrote {len(rows)} records with reasoning -> {out}")
